spring:
  application:
    name: hospitalmanagement

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#     user:
#       name: "abhishek"
#       password: "Virat@17112002"

  security:
    oauth2:
      client:
        registration:

          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope:
              - user:email
              - read:user